### ISSUE TITLE
UniquePtr测试时vector.push_back报错

### ISSUE THREAD

**Issue by chriscco** [parallel101/stl1weekend#9]
note: candidate function not viable: no known conversion from 'Unique_ptr<Dog, DefaultDelete<Dog>>' to 'const Unique_ptr<Animal, DefaultDelete<Animal>>' for 1st argument

似乎是因为没能实现派生类到基类的转换，但是构造函数也没有明显的错误
报错的两行：
https://github.com/chriscco/stl/blob/main/unique_pointer/uniquePointer.cpp#L105-L106
构造函数：
https://github.com/chriscco/stl/blob/main/unique_pointer/uniquePointer.cpp#L42-L45

**Comment by archibate** [comment]
把explicit去掉就行了。

**Comment by archibate** [comment]
不要逮着一个b教程说要加explicit就无脑全部都加，自己都不理解为什么就擅自加了。
```cpp
struct A{};
struct B{
  explicit B(A a);
};
vector<B> v;
v.push_back(A()); // 失败
v.push_back(B(A())); // 成功
```
explicit的效果是让你每次转换的时候都需要强制写出类型名B，所以在你的案例里，需要这样写：
```cpp
vector<UniquePtr<Animal>> v;
v.push_back(makeUnique<Cat>()); // 失败
v.push_back(UniquePtr<Animal>(makeUnique<Cat>())); // 成功
```
才能让编译器找得到explicit的转换构造函数。
解决方案：1.去掉eplicit，2.改用emplace_back，3.手动写这么长一串vector里的完整类型名。
